### ISSUE TITLE
Build error: ModuleNotFoundError: No module named 'setuptools.command.test'

### ISSUE THREAD

**Issue by tekumara** [saulpw/homebrew-vd#16]
```
$ brew install saulpw/vd/visidata
 
....
==> Installing saulpw/vd/visidata
==> python3 -m venv --system-site-packages --without-pip /opt/homebrew/Cellar/visidata/3.0.2_1/libexec
==> python3 -m pip --python=/opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/python install /private/tmp/visidata--six-20240729-548-jvhrmj/six-1.16.0
==> python3 -m pip --python=/opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/python install /private/tmp/visidata--python-dateutil-20240729-548-v4a7cu/pyth
Last 15 lines from /Users/tekumara/Library/Logs/Homebrew/visidata/03.python3:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/python /opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /private/tmp/tmp06sl6bsr
  cwd: /private/tmp/visidata--python-dateutil-20240729-548-v4a7cu/python-dateutil-2.8.2
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python -m pip install --upgrade pip

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/saulpw/homebrew-vd/issues

Warning: Unable to query GitHub for recent issues on the tap
Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]
```

**Comment by tekumara** [comment]
From the logs at /Users/tekumara/Library/Logs/Homebrew/visidata/03.python3:
```
[notice] A new release of pip is available: 24.0 -> 24.2
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pip-build-env-46pri0tz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pip-build-env-46pri0tz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/private/tmp/pip-build-env-46pri0tz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 7, in <module>
  ModuleNotFoundError: No module named 'setuptools.command.test'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/visidata/3.0.2_1/libexec/bin/python /opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/
_in_process.py get_requires_for_build_wheel /private/tmp/tmp06sl6bsr
  cwd: /private/tmp/visidata--python-dateutil-20240729-548-v4a7cu/python-dateutil-2.8.2
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python -m pip install --upgrade pip
```

Looks like https://github.com/pypa/setuptools/issues/4519

**Comment by anjakefala** [comment]
Thanks for letting us know about this!

@tekumara It looks like the maintainers have released a patch of setuptools; are you able to install VisiData now?

**Comment by anjakefala** [comment]
Unfortunately, this is due to a pretty key dependency for VisiData: https://github.com/dateutil/dateutil/issues/1379 I'll keep an eye on this issue, and bump the version of `dateutil` when there's a release.
